[package]
name = "csv2es"
version = "0.1.0"
edition = "2021"

[dependencies]
elasticsearch = "8.5.0-alpha.1"
serde = "1.0.204"
serde_json = "1.0.121"
log = "0.4.22"
femme = "2.2.1"
clap = {  version = "4.5.11", features = ["derive"] }
csv = "1.3.0"

